baseURL = "https://blog.smalltownkitten.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "smalltownkitten"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
featureLen = 250
mainSections = ["post"]
description = "Humorous non-fiction about my interactions, observations, and anxiety"
twitter = "@smalltownkitten"