baseURL = "https://blog.smalltownkitten.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "smalltownkitten"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
featureLen = 1000
mainSections = ["post"]
scripts = [
  "js/clickHandlers.js",
  "js/handleSubRequest.js",
  "js/maintainScroll.js",
  "js/sharePost.js"
]
