baseURL = "https://blog.smalltownkitten.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "smalltownkitten"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[module]
  [[module.imports]]
    path = "github.com/sarahlehman/smalltownkitten-theme"

[params]
title = "I'm Sarah"
author = "Sarah Lehman"
description = "I grew up in rural Pennsylvania and now I’m an adult in rural Pennsylvania (I refuse to use the word “adulting” even though it admittedly would’ve flowed better there.) I write about things I observe and things that happen to me. Some days I like my cat more than I like myself, but I’m working on it."
profilePicture = "/sarah.png"
keywords = ""
favicon = "/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sarahlehman"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/smalltownkitten"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:sarah@smalltownkitten.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Posts"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Index"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"

  [server]

  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Content-Security-Policy = "script-src localhost:1313 blog.serv.home:1313"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Access-Control-Allow-Origin = "*"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"