baseURL = "https://blog.smalltownkitten.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "smalltownkitten"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[module]
  [[module.mounts]]
    source = "./node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"

[params]
title = "I'm Sarah"
author = "Sarah Lehman"
featureLen = 1000
mainSections = ["post"]
  
  [server]

  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Content-Security-Policy = "script-src localhost:1313 blog.serv.home:1313 'unsafe-inline'"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Access-Control-Allow-Origin = "*"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"