[server]

  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Content-Security-Policy = "script-src localhost:1313 blog.serv.home:1313 'unsafe-inline'"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Access-Control-Allow-Origin = "*"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
