# This is a basic workflow to help you get started with Actions

name: Publish Content

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
     - 'content/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - shell: pwsh
        env:
          DEPLOY_HOOKS: ${{ secrets.DEPLOYHOOKS }}
        
      # Runs a set of commands using the runners shell
      - name: Hit Deploy Hooks
        run: |
          $env:DEPLOY_HOOKS -split ',' | ForEach-Object -Process {if ((Invoke-Webrequest $_).StatusCode -ne 200) { Write-Error "deploy fail" }}
